#
# Flownative Auth0 Routes
#

-
  name: 'Flownative Auth0 Client: test'
  uriPattern: '_/flownative/auth0/{@action}'
  defaults:
    '@package':    'Flownative.Auth0'
    '@controller': 'Auth0'
    '@action': 'index'
  appendExceedingArguments: true
