Flownative:
  Auth0:
    # The domain of your Auth0 application's identity provider
    # For example "example.eu.auth0.com" or "id.custom-domain.com"
    domain: '%env:FLOWNATIVE_AUTH0_DOMAIN%'

    # Credentials for your Auth0 Application
    clientId: '%env:FLOWNATIVE_AUTH0_CLIENT_ID%'
    clientSecret: '%env:FLOWNATIVE_AUTH0_CLIENT_SECRET%'
